_short_name: "2DMamba"
class_name: TwoDMamba
input_dim: 192
input_shape: [224, 224, 3]
output_shape: [2]
patch_size: 16

dims:
  - ${..input_dim}
  - ${..input_dim}
  - ${..input_dim}
  - ${..input_dim}

depths: [2, 2, 5, 2]
ssm_d_state: 1
ssm_dt_rank: "auto"
ssm_ratio: 2.0
ssm_conv: 3
ssm_conv_bias: false
ssm_forward_type: "v05_noz"
mlp_ratio: 4.0
downsample: "v3"
patchembed: "v2"
norm_layer: "ln2d"
use_v2d: true

num_classes: ${.output_shape.0}
image_size: ${.input_shape.0}

aux: {}
