defaults:
  - plstm_vision

norm:
  class_name: LayerNorm
  eps: 1.0e-06
  bias: true

block_stack:
  block:
    block0:
      use_scale: true
      scale:
        input_dim: ${..input_dim}
        class_name: ScaleLayer
        scale_init:
          class_name: ConstantInit
          value: 1e-4
      norm:
        class_name: LayerNorm
        bias: true
        eps: 1.0e-06
      interaction_module:
        direct:
          weight_init:
            axis: -1
            class_name: SmallInit
        key:
          weight_init:
            axis: -1
            class_name: SmallInit
            mup_init_scale: 1.0
        mark:
          weight_init:
            axis: -1
            class_name: SmallInit
        outprojection_weight_init:
          axis: -1
          class_name: SmallInit
          mup_init_scale: 1.0
        pmode_orientation_weight_init:
          axis: -1
          class_name: SmallInit
        query:
          weight_init:
            axis: -1
            class_name: SmallInit
            mup_init_scale: 1.0
        source:
          weight_init:
            axis: -1
            class_name: SmallInit
        transition:
          eigenvalue_weight_init:
            axis: -1
            class_name: SmallInit
        value:
          weight_init:
            axis: -1
            class_name: SmallInit
            mup_init_scale: 1.0
        mhnorm:
          class_name: MultiHeadLayerNorm

    block1:
      use_scale: true
      scale:
        input_dim: ${..input_dim}
        class_name: ScaleLayer
        scale_init:
          class_name: ConstantInit
          value: 1e-4
      norm:
        class_name: LayerNorm
        bias: true
        eps: 1.0e-06
      interaction_module:
        mhnorm:
          class_name: MultiHeadLayerNorm
        direct:
          weight_init:
            axis: -1
            class_name: SmallInit
        key:
          weight_init:
            axis: -1
            class_name: SmallInit
            mup_init_scale: 1.0
        mark:
          weight_init:
            axis: -1
            class_name: SmallInit
        outprojection_weight_init:
          axis: -1
          class_name: SmallInit
          mup_init_scale: 1.0
        pmode_orientation_weight_init:
          axis: -1
          class_name: SmallInit
        query:
          weight_init:
            axis: -1
            class_name: SmallInit
            mup_init_scale: 1.0
        source:
          weight_init:
            axis: -1
            class_name: SmallInit
        transition:
          eigenvalue_weight_init:
            axis: -1
            class_name: SmallInit
        value:
          weight_init:
            axis: -1
            class_name: SmallInit
            mup_init_scale: 1.0
