class_name: CIFAR10Dataset
_short_name: "cf10"
data_dir: ${oc.env:DATA_DIR}
global_batch_size: 128
local_batch_size: 128
# batch_size: 128
num_workers: 8
resolution: [32, 32]
num_channels: 3
channels_first: false
num_classes: 10
normalize: false
val_size: 5000

aux:
  steps_per_epoch: ${oc.floor_divide:${oc.subi:50000,${..val_size}},${..global_batch_size}}
